{
 "title": "Alibaba CDN Logs - Raw Table - Real-TIme",
 "tags": [
  "cdn",
  "logs",
  "athena",
  "real-time"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "client_ip", "label": "Client IP" },
   { "name": "http_status", "label": "HTTP Status" },
   { "name": "request_url", "label": "Request URL (contains)" },
   { "name": "response_time", "label": "Min Response Time" },
   { "name": "http_method", "label": "HTTP Method" },
   { "name": "user_agent", "label": "User Agent" },
   { "name": "cache_status", "label": "Cache Status" },
   { "name": "referrer", "label": "Referrer" }
  ]
 },
 "panels": [
  {
   "title": "TOP 10 Client_IP",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "query": "* |\r\nSELECT\r\n    client_ip,\r\n    COUNT(*) AS total_requests\r\nWHERE\r\n (${http_method:sqlstring} = '' OR method = ${http_method:sqlstring})\r\n    AND (${request_url:sqlstring} = '' OR uri LIKE CONCAT('%', ${request_url:sqlstring}, '%'))\r\n    AND (${client_ip:sqlstring} = '' OR client_ip LIKE CONCAT('%', ${client_ip:sqlstring}, '%'))\r\n    AND (${cache_status:sqlstring} = '' OR hit_info = ${cache_status:sqlstring})\r\n    AND (${http_status:sqlstring} = '' OR CAST(return_code AS VARCHAR) = ${http_status:sqlstring})\r\n    AND (${user_agent:sqlstring} = '' OR user_agent LIKE CONCAT('%', ${user_agent:sqlstring}, '%'))\r\n    AND (${referrer:sqlstring} = '' OR refer_domain LIKE CONCAT('%', ${referrer:sqlstring}, '%'))\r\nGROUP BY\r\n    client_ip\r\nORDER BY\r\n    total_requests DESC\r\nLIMIT 10\r\n",
     "totalLogs": 100,
     "type": "all"
    }
   ]
  },
  {
   "title": "TOP Channel",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "query": "* |\r\nSELECT\r\n    regexp_extract(uri, '/live/([^/]+)/', 1) as channel,\r\n    COUNT(*) AS total_requests\r\nWHERE\r\n  (${http_method:sqlstring} = '' OR method = ${http_method:sqlstring})\r\n    AND (${request_url:sqlstring} = '' OR uri LIKE CONCAT('%', ${request_url:sqlstring}, '%'))\r\n    AND (${client_ip:sqlstring} = '' OR client_ip LIKE CONCAT('%', ${client_ip:sqlstring}, '%'))\r\n    AND (${cache_status:sqlstring} = '' OR hit_info = ${cache_status:sqlstring})\r\n    AND (${http_status:sqlstring} = '' OR CAST(return_code AS VARCHAR) = ${http_status:sqlstring})\r\n    AND (${user_agent:sqlstring} = '' OR user_agent LIKE CONCAT('%', ${user_agent:sqlstring}, '%'))\r\n    AND (${referrer:sqlstring} = '' OR refer_domain LIKE CONCAT('%', ${referrer:sqlstring}, '%'))\r\nGROUP BY\r\n    channel\r\nORDER BY\r\n    total_requests DESC\r\nLIMIT 10\r\n",
     "totalLogs": 100,
     "type": "all"
    }
   ]
  },
  {
   "title": "TOP Long Token",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "query": "* |\r\nSELECT\r\n    regexp_extract(uri, '/([^/]+)/live/', 1) as token,\r\n    COUNT(*) AS total_requests\r\nWHERE\r\n (${http_method:sqlstring} = '' OR method = ${http_method:sqlstring})\r\n    AND (${request_url:sqlstring} = '' OR uri LIKE CONCAT('%', ${request_url:sqlstring}, '%'))\r\n    AND (${client_ip:sqlstring} = '' OR client_ip LIKE CONCAT('%', ${client_ip:sqlstring}, '%'))\r\n    AND (${cache_status:sqlstring} = '' OR hit_info = ${cache_status:sqlstring})\r\n    AND (${http_status:sqlstring} = '' OR CAST(return_code AS VARCHAR) = ${http_status:sqlstring})\r\n    AND (${user_agent:sqlstring} = '' OR user_agent LIKE CONCAT('%', ${user_agent:sqlstring}, '%'))\r\n    AND (${referrer:sqlstring} = '' OR refer_domain LIKE CONCAT('%', ${referrer:sqlstring}, '%'))\r\nGROUP BY\r\n    token\r\nORDER BY\r\n    total_requests DESC\r\nLIMIT 10\r\n",
     "totalLogs": 100,
     "type": "all"
    }
   ]
  },
  {
   "title": "Total Request (over 5mn period)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "query": "*\r\n| select \r\n    __time__ - (__time__ % 300) as time,\r\n        COUNT(*) AS total_requests\r\nfrom log\r\nWHERE\r\n     (${http_method:sqlstring} = '' OR method = ${http_method:sqlstring})\r\n    AND (${request_url:sqlstring} = '' OR uri LIKE CONCAT('%', ${request_url:sqlstring}, '%'))\r\n    AND (${client_ip:sqlstring} = '' OR client_ip LIKE CONCAT('%', ${client_ip:sqlstring}, '%'))\r\n    AND (${cache_status:sqlstring} = '' OR hit_info = ${cache_status:sqlstring})\r\n    AND (${http_status:sqlstring} = '' OR CAST(return_code AS VARCHAR) = ${http_status:sqlstring})\r\n    AND (${user_agent:sqlstring} = '' OR user_agent LIKE CONCAT('%', ${user_agent:sqlstring}, '%'))\r\n    AND (${referrer:sqlstring} = '' OR refer_domain LIKE CONCAT('%', ${referrer:sqlstring}, '%'))\r\nGROUP BY\r\n    time\r\nORDER BY\r\n    time\r\n",
     "totalLogs": 100,
     "type": "all",
     "xcol": "time"
    }
   ]
  },
  {
   "title": "Total Unique Values",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "query": "*\r\n| select\r\n    count(*) as total_requests,\r\n    approx_distinct(client_ip) AS client_ip,\r\n    approx_distinct(refer_domain) AS referrer,\r\n  \r\n    approx_distinct(method) AS http_method,\r\n    approx_distinct(regexp_extract(uri, '/live/([^/]+)/', 1)) AS channels,\r\n    approx_distinct(regexp_extract(uri, '/live/[^/]+/([^/]+)', 1)) AS file_name,\r\n    approx_distinct(regexp_extract(uri, '/([^/]+)/live/', 1)) AS long_token,\r\n    approx_distinct(uri) AS request_url,\r\n\r\n    approx_distinct(return_code) AS http_status,\r\n    approx_distinct(hit_info) AS cache_status,\r\n    approx_distinct(user_agent) AS user_agent,\r\n    approx_distinct(content_type) AS file_type,\r\n    approx_distinct(domain) AS access_ip\r\nfrom log\r\nwhere\r\n  ('${http_method}' = '' OR method = '${http_method}')\r\n  AND ('${request_url}' = '' OR uri LIKE CONCAT('%', '${request_url}', '%'))\r\n  AND ('${client_ip}' = '' OR client_ip LIKE CONCAT('%', '${client_ip}', '%'))\r\n  AND ('${cache_status}' = '' OR hit_info = '${cache_status}')\r\n  AND ('${http_status}' = '' OR CAST(return_code AS VARCHAR) = '${http_status}')\r\n  AND ('${user_agent}' = '' OR user_agent LIKE CONCAT('%', '${user_agent}', '%'))\r\n  AND ('${referrer}' = '' OR refer_domain LIKE CONCAT('%', '${referrer}', '%'))\r\n",
     "totalLogs": 100,
     "type": "all",
     "xcol": "stat"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "query": "*\r\n| select\r\n    __time__ AS time,\r\n    client_ip,\r\n    return_code AS http_status,\r\n    method AS http_method,\r\n    regexp_extract(uri, '/live/([^/]+)/', 1) as channel_name,\r\n    regexp_extract(uri, '/live/[^/]+/([^/]+)', 1) as file_name,\r\n    regexp_extract(uri, '/([^/]+)/live/', 1) as long_token,\r\n\r\n    uri AS request_url,\r\n    uri_param,\r\n    user_agent,\r\n    content_type AS file_type,\r\n    request_time AS response_time,\r\n    refer_domain AS referrer,\r\n    request_size AS request_bytes,\r\n    response_size AS response_bytes,\r\n    hit_info AS cache_status,\r\n    domain AS access_ip\r\nfrom log\r\nwhere\r\n  ('${http_method}' = '' OR method = '${http_method}')\r\n  AND ('${request_url}' = '' OR uri LIKE CONCAT('%', '${request_url}', '%'))\r\n  AND ('${client_ip}' = '' OR client_ip LIKE CONCAT('%', '${client_ip}', '%'))\r\n  AND ('${cache_status}' = '' OR hit_info = '${cache_status}')\r\n  AND ('${http_status}' = '' OR CAST(return_code AS VARCHAR) = '${http_status}')\r\n  AND ('${user_agent}' = '' OR user_agent LIKE CONCAT('%', '${user_agent}', '%'))\r\n  AND ('${referrer}' = '' OR refer_domain LIKE CONCAT('%', '${referrer}', '%'))\r\nlimit 1000",
     "totalLogs": 100,
     "type": "all"
    }
   ]
  }
 ]
}